## **<center> LVTN: PHÁT TRIỂN ỨNG DỤNG DI ĐỘNG QUẢN LÍ LỚP HỌC ONLINE VÀ TRỢ GIẢNG </center>**
***
<br>

Bài toán đặt ra: 

*   Học sinh thường học tốt và hứng thú với một số môn nhất định.
*   Các môn học tốt, học sinh có nhu cầu luyện tập, tìm hiểu nhiều hơn.
*   Các môn học không có hứng thú, học sinh có nhu cầu đạt được một mức nhất định
*   Cần có những cách thức để đưa ra những bài tập phù hợp với năng lực học sinh, giúp học sinh có khả năng phát triển tốt nhất đối với các môn học.

Hướng giải quyết: <br>
> Trong các bài tập tự luyện, mỗi học sinh sẽ được phân chia làm những gói câu hỏi riêng biệt. Dựa vào những kết quả của bài làm trước, mô hình Machine Learning sẽ đánh giá, và đưa ra gói câu hỏi tiếp theo phù hợp với năng lực từng học sinh. 

[Link dữ liệu](https://drive.google.com/file/d/1OUHqOoQLOK-dp2Y4TmphbNx3v-jbQUL-/view?usp=sharing)








# **Hiện thực**

#**Xử lí dữ liệu**

**Thiết lập Google Drive**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
data_dir="/content/drive/MyDrive/Thesis/thesis.csv"

Mounted at /content/drive


**Cài đặt các modules**

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split


**Xử lí dữ liệu**

In [ ]:
data = pd.read_csv(data_dir)
data = data.dropna()
data1 = data[~(data.level>5)]
data2 = data1[~(data1.speed<5)]
data3 = data2[~(data2.score_1>10)]
data3.head()

score_1  package_1  score_2  package_2  score_3  package_3  speed  \
0        8          2        7          3        8          3     45   
1        3          1        6          1        4          1     58   
2        5          1        7          1        7          2     55   
3        8          3       10          3       10          4     45   
4        7          2        6          2        9          3     50   

   satisfied_level  level  
0              4.0      3  
1              4.0      1  
2              4.0      2  
3              5.0      5  
4              4.5      3

In [ ]:
data3.shape

(403, 9)

In [ ]:
X = data3[data3.columns[0:8]].values
y = data3['level'].values
X

array([[ 8. ,  2. ,  7. , ...,  3. , 45. ,  4. ],
       [ 3. ,  1. ,  6. , ...,  1. , 58. ,  4. ],
       [ 5. ,  1. ,  7. , ...,  2. , 55. ,  4. ],
       ...,
       [ 9. ,  1. ,  7. , ...,  3. , 55. ,  3.5],
       [ 7. ,  1. ,  8. , ...,  3. , 50. ,  3. ],
       [ 7. ,  1. ,  9. , ...,  2. , 59. ,  3.5]])

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
X_test


array([[ 9. ,  2. , 10. ,  3. ,  9. ,  4. , 41. ,  4.5],
       [ 7. ,  2. ,  6. ,  2. ,  5. ,  3. , 49. ,  4. ],
       [ 9. ,  2. , 10. ,  3. , 10. ,  3. , 33. ,  5. ],
       [ 8. ,  1. ,  9. ,  2. , 10. ,  3. , 44. ,  4. ],
       [ 6. ,  1. ,  8. ,  2. ,  7. ,  3. , 47. ,  5. ],
       [ 8. ,  3. , 10. ,  3. , 10. ,  4. , 45. ,  5. ],
       [ 7. ,  1. ,  8. ,  2. ,  8. ,  3. , 57. ,  4. ],
       [ 7. ,  1. ,  8. ,  2. ,  9. ,  3. , 54. ,  4.5],
       [ 9. ,  1. ,  7. ,  2. ,  8. ,  3. , 50. ,  4. ],
       [ 7. ,  2. ,  8. ,  3. ,  6. ,  4. , 55. ,  3. ],
       [ 4. ,  1. ,  6. ,  1. ,  5. ,  2. , 49. ,  3.5],
       [ 7. ,  1. ,  5. ,  2. ,  8. ,  2. , 39. ,  4. ],
       [ 7. ,  3. ,  8. ,  3. ,  8. ,  4. , 40. ,  4.5],
       [ 9. ,  3. , 10. ,  3. , 10. ,  4. , 62. ,  4.5],
       [ 3. ,  1. ,  7. ,  1. ,  7. ,  2. , 47. ,  4. ],
       [ 7. ,  2. ,  8. ,  2. ,  9. ,  3. , 30. ,  5. ],
       [ 5. ,  2. ,  8. ,  2. , 10. ,  3. , 33. ,  4.5],
       [ 8. ,  2. ,  9. ,  3. ,

#**Thử nghiệm các mô hình**

**Thử nghiệm mô hình LogisticRegression (Softmax Regression)**

In [ ]:
from sklearn.linear_model import LogisticRegression
softmaxReg = LogisticRegression(multi_class = 'multinomial', solver = 'lbfgs')
softmaxReg.fit(X_train,y_train)
softmaxReg.score(X_test,y_test)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


0.5802469135802469

**Thử nghiệm mô hình SVM (Support Vector Machine)**

In [ ]:
from sklearn import svm
svm_model = svm.SVC(kernel='linear',C=10,gamma='auto')
svm_model.fit(X_train,y_train)
svm_model.score(X_test, y_test)

0.8888888888888888

#**Đánh giá các mô hình sử dụng GridSearchCV**

In [ ]:
# Đánh giá 

In [ ]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV

cv = ShuffleSplit(n_splits=3, test_size=0.2, random_state=0)

cross_val_score(LogisticRegression(multi_class = 'multinomial', solver = 'lbfgs'), X, y, cv=cv)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


array([0.65432099, 0.67901235, 0.62962963])

In [ ]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

model_params = {
    'svm': {
        'model': svm.SVC(gamma='auto'),
        'params' : {
            'C': [1,10,20],
            'kernel': ['rbf','linear']
        }  
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params' : {
            'n_estimators': [1,5,10]
        }
    },
    'logistic_regression' : {
        'model': LogisticRegression(solver='liblinear',multi_class='auto'),
        'params': {
            'C': [1,5,10]
        }
    }
}

In [ ]:
scores = []

for model_name, mp in model_params.items():
    clf =  GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(X, y)
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })
    
df = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df

model  best_score                    best_params
0                  svm    0.888395  {'C': 20, 'kernel': 'linear'}
1        random_forest    0.858765            {'n_estimators': 5}
2  logistic_regression    0.665154                      {'C': 10}

#**Thử nghiệm với các dữ liệu đưa vào và xuất mô hình**

In [ ]:

x_test= np.array([[10,3,9,3,9,4,54,4]])
y_expect = svm_model.predict(x_test)
y_expect

array([5])

In [ ]:
import pickle
with open('thesis.pickle','wb') as f:
    pickle.dump(svm_model,f)

In [ ]:
import json
columns = {
    'data_columns' : [col.lower() for col in data.columns[0:8]]
}
with open("columns.json","w") as f:
    f.write(json.dumps(columns))